### ISSUE TITLE
gradle dependency

### ISSUE THREAD

**Issue by meeDamian** [Serchinastico/CoolSwitch#1]
Sooner or later somebody would create this issue anyway ;).

Publish to Ant/Maven so it can be imported as a gradle dependency.

**Comment by ZieIony** [comment]
for now you can use JitPack:

https://jitpack.io/#Serchinastico/CoolSwitch/1.0.0

**Comment by Serchinastico** [comment]
As Zielony said, for now you can use it directly from JitPack but I'll publish it in maven anytime soon.

**Comment by Drakot** [comment]
Yes please, the lib looks very nice. I will implement it when it supports gradle.

**Comment by mgursch** [comment]
+1

**Comment by Serchinastico** [comment]
It took me more than I thought but here it is:

Maven Central: http://search.maven.org/#artifactdetails%7Ccom.github.serchinastico%7Ccoolswitch%7C1.0.1%7Caar
JCenter: https://bintray.com/serchinastico/maven/CoolSwitch/

I'll add a short include example for maven/gradle in the project description.

Thank you all!
