### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MostafaSh** [Serchinastico/CoolSwitch#5]
Hi,
I have a problem.
when I add the CoolSwitch lib through dependencies into my project, I get this error:

Error:Failed to resolve: com.github.ozodrukh:CircularReveal:1.0.4
<a href="openFile:C:/Users/Dena Computer/AndroidStudioProjects/ScreenFilter/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

what can I do to resolve it?

**Comment by eyalgofer** [comment]
You can add remote maven, like this:
	repositories {
	    maven {
	        url "https://jitpack.io"
	    }
	}
solved the issue for me :)

**Comment by Serchinastico** [comment]
To be honest, I think the CircularReveal library is not used anymore so we can safely remove it but this project is no longer being supported. PRs are more than welcome, though.
